name: coverage-report

on:
  push:
    branches:
      - main

jobs:
  coverage-report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up python runtime
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: set up python configuration
        run: |
          pip install -U pip
          pip install tox codecov

      - name: retest
        run: |
          tox -e py39

      - name: coverage report
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          codecov
