name: major-release-request

on:
  workflow_dispatch:

jobs:
  release-pr:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: configure npm
        run: npm ci
        working-directory: ./release

      - name: set version
        id: set_version
        run: |
          npm run release:major -- \
            -i ../CHANGELOG.md \
            --commitUrlFormat="https://github.com/${GITHUB_REPOSITORY}/commit/{{hash}}" \
            --compareUrlFormat="https://github.com/${GITHUB_REPOSITORY}/compare/{{previousTag}}...{{currentTag}}"
          echo "::set-output name=version::$(jq -r .version package.json)"
        working-directory: ./release

      - name: update python package version
        run: |
          sed -i 's/^__version__.*/__version__ = "${{steps.set_version.outputs.version}}"/' src/create_github_project/__init__.py

      - name: update install command
        run: |
          sed -i 's/create-github-project@v[0-9]\{1,\}\(\.[0-9]\{1,\}\)\{2\}/create-github-project@v${{steps.set_version.outputs.version}}/' README.md

      - name: set pull request body
        run: |
          body=$(sed -e 's/^#\(#*\) \[/#\1 /' \
                     -e '1,/^## ${{steps.set_version.outputs.version}}/d' \
                     -e '/^##* [0-9]/,$d' \
                     CHANGELOG.md)
          echo 'BODY<<EOF' >> $GITHUB_ENV
          echo "${body}" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: create pull request for major release
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "chore: release v${{ steps.set_version.outputs.version }}"
          author: "GitHub Action <41898282+github-actions[bot]@users.noreply.github.com>"
          title: "chore: release ${{ steps.set_version.outputs.version }}"
          body: |
            ## 変更点
            ${{ env.BODY }}
          labels: automated pr
          base: main
          branch: release-v${{ steps.set_version.outputs.version }}
          delete-branch: true
