name: test

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  run-test:
    runs-on: ${{ matrix.platform }}
    strategy:
      max-parallel: 10
      matrix:
        platform: [ubuntu-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2

      - name: set up python
        run: |
          pip install .
          pip install -r tests/test_requirements.txt

      - name: run test
        run: |
          pytest --cov=./src/create_github_project --cov-branch tests
