name: test

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  run-test:
    runs-on: ${{ matrix.platform }}
    strategy:
      max-parallel: 10
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        params:
          - py_ver: "3.7"
            tox_env: "py37"
          - py_ver: "3.8"
            tox_env: "py38"
          - py_ver: "3.9"
            tox_env: "py39"

    steps:
      - uses: actions/checkout@v2

      - name: set up python runtime
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.params.py_ver }}

      - name: set up python configuration
        run: |
          pip install -U pip
          pip install tox

      - name: configure git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: run test
        run: |
          tox -e ${{ matrix.params.tox_env }}

  coverage-report:
    needs: run-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up python runtime
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: set up python configuration
        run: |
          pip install -U pip
          pip install tox

      - name: configure git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: retest
        run: |
          tox -e py39

      - name: coverage report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
