name: test

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  run-test:
    runs-on: ${{ matrix.platform }}
    strategy:
      max-parallel: 10
      matrix:
        platform: [ubuntu-latest, macos-latest]
        params:
          - py_ver: "3.7"
            tox_env: "py37"
          - py_ver: "3.8"
            tox_env: "py38"
          - py_ver: "3.9"
            tox_env: "py39"

    steps:
      - uses: actions/checkout@v2

      - name: set up python runtime
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py_ver }}

      - name: set up python configuration
        run: |
          pip install -U pip
          pip install tox tox-gh-actions

      - name: run test
        run: |
          tox -e ${{ matrix.tox_env }}
